# Mémoire et encodage (Ajout de UTF-8 indispensable sur Windows)
org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=1G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

# AndroidX (Standard)
android.useAndroidX=true
android.enableJetifier=true

# Optimisations de build
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.daemon=true
org.gradle.configureondemand=true